package pv_admin;

public class Landingpage_repository {
	
	static final String url_landingpage="https://qapoc.sgligis.com:10013/";
	static final String logo="//a[@class='logo']";
	static final String logo_text="//a[@class='logo']/span";
	static final String header="//header";
	static final String maincontent_homepage="//h1[@id='main-content']";
	static final String lnk_Home="//a[text()='Home']";
	static final String lnk_Services="//div[@class='main-menu']/div/div[2]/nav/ul/li[2]";
	static final String lnk_CaptureCrime="//div[@class='main-menu']/div/div[2]/nav/ul/li[4]";
	static final String lnk_Skiptomaincontent="//a[contains(text(),'Skip To Main Content')]";
	static final String text_Skiptomaincontent="//a[text()='Skip to Main Content']";
	static final String lnk_red_color="//a[@class='red color-box']";
	static final String lnk_white_color="//a[@class='white color-box']";
	static final String lnk_yellow_color="//a[@class='yellow color-box']";
	static final String lnk_green_color="//a[@class='green color-box']";
	static final String lnk_decrease_fontsize="//a[@class='decrease-font']";
	static final String lnk_default_fontsize="(//a[text()='A'])[2]";
	static final String lnk_increase_fontsize="//a[@class='increase-font']";
	static final String lang_dd="//header/div[@class='container-fluid']/div[1]/div/ul/li[5]/div";
	static final String lang_op="//header/div[@class='container-fluid']/div[1]/div/ul/li[5]/div/div";
	static final String lan_lnk="//header/div[@class='container-fluid']/div[1]/div/ul/li[5]/div/a/span[2]";
	static final String btn_GotoMap="//div[@class='main-menu']/div/div[2]/nav/ul/li[5]/a/span[2]";
	static final String Mapcontainer="//div[@class='sgl_igis_3d-container']";
	static final String btn_Login="//a[@class='signbtn']";
	static final String txt_admin="//a[@class='dropdown-toggle btn']";
	static final String dd_admin="//a[@class='dropdown-toggle btn']";
	static final String dd_admin_op1="//div[@class='col-md-12 right-text']/ul/li[6]/div/div[2]/a[1]";
	static final String dd_admin_op2="//div[@class='col-md-12 right-text']/ul/li[6]/div/div[2]/a[2]";
	static final String dd_admin_op3="//div[@class='col-md-12 right-text']/ul/li[6]/div/div[2]/a[3]";
	static final String newsevent_section="//div[@class='news-event']";
	static final String next_arrow_newssection="//button[@class='slick-next slick-arrow']";
	static final String pre_arrow_newssection="//button[@class='slick-prev slick-arrow']";
	static final String slide_control0="//button[@id='slick-slide-control00']";
	static final String slide_control2="//button[@id='slick-slide-control02']";
	static final String slide_control5="//button[@id='slick-slide-control05']";
	static final String slidetrack_newssection="//div[@class='slick-track']";
	static final String slidedots_newsection="//ul[@class='slick-dots']";
	static final String newsletter_section="//div[@class='newsleter-wrap']";
	static final String btn_clear="(//div[1]//button[@class='btn btn-default'])[1]";
	static final String btn_clear_raisesec="(//div[1]//button[@class='btn btn-default'])[2]";
	static final String sec_reportcrime="//li[@data-id='report_crime']";
	static final String sec_raisecomplaint="//li[@data-id='raise_complaint']";
	static final String dd_sel_crimetype="//div[@id='report_crime']/form/div[1]/select[@class='form-control']";
	static final String dd_sel_crimesubtype="//div[@id='report_crime']/form/div[2]/select[@class='form-control']";
	static final String dd_op_crimetype3="//*[text()='Crime Type3']";
	static final String dd_op_crimesubtype3="//*[text()='Crime Sub-type3']";
	static final String dd_op_crimetype3_raise="(//*[text()='Crime Type3'])[2]";
	static final String dd_op_crimesubtype3_raise="(//*[text()='Crime Sub-type3'])[2]";
	static final String dd_sel_crimetype_raise="//div[@id='raise_complaint']/form/div[1]/select[@class='form-control']";
	static final String dd_sel_crimesubtype_raise="//div[@id='raise_complaint']/form/div[2]/select[@class='form-control']";
	static final String txt_policebandobast="//*[text()='Police Bandobast']";
	static final String txt_crimeanalysis="//*[text()='Crime Analysis']";
	static final String footer_allrights="//div[@class='last-footer']";
	static final String txt_uploadphoto1="//*[text()='upload Crime Photo1']";
	static final String btn_raisecom="//button[text()='Raise Complaint']";
	static final String txt_title_CrimeMapping="//div[@class='col-md-6 bg-img-text animation-init animation-animate']/div/h2";
	static final String txt_para_CrimeMapping="//div[@class='col-md-6 bg-img-text animation-init animation-animate']/div/p";
	static final String txt_newfooter_lnk="//a[text()='Achivements1']";
	static final String img_newadded="//ul[@class='photos-grp']/li[5]";
	static final String btn_LiveChat="//a[text()='Live Chat']";
	static final String btn_Signup="//a[text()='SIGN UP']";
	static final String txt_policepatrolling="//h2[text()='Police Patrolling']";
	static final String txt_surveillancesystems="//h2[text()='Surveillance Systems']";
	static final String txt_citizensos="//h2[text()='Citizen SOS Services']";
	static final String footer_sec="//footer";
	static final String reportcrime_sec="//div[@class='form-block animation-init animation-animate']";
	static final String navpath_3="//ul[@class='breadcrumb']/li[3]/a";
	static final String navpath_2="//ul[@class='breadcrumb']/li[2]/a";
	static final String txt_gallery="//h2[text()='Gallery']";
	static final String header_contentpage="//div[@class='container']/div[2]/h2";
	static final String lnk_citizencharter="//a[text()='Citizen’s Charter']";
	static final String lnk_Contactus="//a[text()='Contact us']";
	static final String lnk_feedback="//a[text()='Feedback']";
	static final String dd_topic_feedback="//select[@id='Topic']";
	static final String txtbox_visitorname_feedback="//input[@id='visitorName']";
	static final String btn_submit_feedback="//button[@class='submit-btn']";
	static final String txtarea_feedback="//textarea[@id='inputFeedback']";
	static final String searchbox="//input[@type='search']";
	static final String lnk_aboutus="//a[text()='About us ▾']";
	static final String lnk_origin="//a[text()='Origin']";
	static final String lnk_activities="//a[text()='Activities']";
	static final String lnk_organization="//a[text()='Organization']";
	static final String lnk_dictormsg="//a[text()='Director Message']";
	static final String lnk_CCTNS="//a[text()='CCTNS']";
	static final String lnk_centralfingerprintbureau="//a[text()='Central Finger Print Bureau']";
	static final String lnk_statisticalbranch="//a[text()='Statistical Branch']";
	static final String lnk_trainingbranch="//a[text()='Training Branch']";
	static final String lnk_datacentreandtechbranch="//a[text()='Data Centre and Technical Branch']";
	static final String lnk_home_contentpage="//div[@class='container']//a[text()='Home']";
	static final String lnk_divisions="//a[text()='Divisions ▾']";
	static final String lnk_CCT="//a[text()='Crime & Criminal Tracking (CCT)']";
	static final String lnk_DCT="//a[text()='Data Centre & Technical Branch (DCT) ']";
	static final String lnk_aboutCCTNS="//a[text()='About CCTNS ']";
	static final String lnk_CCTNSimpleFramework="//a[text()='CCTNS Implementation Framework ']";
	static final String lnk_vision_and_objofCCTNS="//a[text()='Vision and Objectives of CCTNS ']";
	static final String lnk_stakeholderofproj="//a[text()='Stakeholders of Project ']";
	static final String lnk_benefitsofCCTNS="//a[text()='Benefits of CCTNS ']";
	static final String lnk_publications="//a[text()='Publications ▾']";
	static final String lnk_crimeinIndia="//a[text()='Crime in India']";
	static final String lnk_prisonstatistics="//a[text()='Prison Statistics India']";
	static final String lnk_reportonmissing_women_and_chil="//a[text()='Report on Missing Woman & Children']";
	static final String lnk_citizen_services="//a[text()='Citizen Sevices ▾']";
	static final String lnk_cybercrimereportingportal="//a[text()='Cyber Crime Reporting Portal']";
	static final String lnk_generatevehicleNOC="//a[text()='Generate Vehicle NOC']";
	static final String lnk_shortfileonCCTNS="//a[text()='Short Film on CCTNS Citizen Services']";
	static final String lnk_notifications="//a[text()='Notifications ▾']";
	static final String lnk_vacancies="//a[text()='Vacancies']";
	static final String lnk_advisories="//a[text()='Advisories']";
	static final String lnk_RTI="//a[text()='RTI']";
	
	//xpath of admin portal used in Landing Page
	static final String btn_returnapp="//a[@id='returnUrlLink']";
	static final String dd_CMS="//div[@id='mCSB_1_container']/nav/ul/li[5]/a/span[@class='lp-text']";
	static final String dd_op_Pages="//div[@class='mCSB_container']/nav/ul/li[5]/ul/li[1]";
	static final String page_header="//div[@class='col-auto']/h1";
	static final String btn_Actions_logo="//div[@class='dataTables_scrollBody']/table/tbody/tr[4]/td/div/button";
	static final String btn_edit="//ul[@class='dropdown-menu show']/li[1]";
	static final String btn_delete="//ul[@class='dropdown-menu show']/li[2]";
	static final String content_page_CMS="//form[@id='form-page-update']/div[5]/ul/li[1]/a";
	static final String txt_logo_CMS="//pre[@class=' CodeMirror-line '][12]/span/span[4]";
	static final String btn_submit_CMS="//button[@id='button-page-update']";
	static final String span1="//pre/span[@role='presentation']/span[4]";
	static final String span2="//pre/span[@role='presentation']/span[6]";
	static final String numbering_CMS_1="//div[@class='row dataTable_footer']/div[3]/div/ul/li/a[@data-dt-idx='1']";
	static final String numbering_CMS_3="//div[@class='row dataTable_footer']/div[3]/div/ul/li/a[@data-dt-idx='3']";
	static final String btn_Actions_CrimeMapping="//div[@class='dataTables_scrollBody']/table/tbody/tr[6]/td/div/button";
	static final String text_CrimeMapping="//div[@class='CodeMirror-code']/pre[7]";
	static final String btn_Actions_footer="//div[@class='dataTables_scrollBody']/table/tbody/tr[2]/td/div/button";
	static final String btn_Actions_gallery="//div[@class='dataTables_scrollBody']/table/tbody/tr[10]/td/div/button";
	static final String btn_NewPage="//button[@name='CreatePage']";
	static final String txtbox_title_CMSpage="//input[@id='ViewModel_Title']";
	static final String txtbox_Slug_CMSpage="//input[@id='ViewModel_Slug']";
	static final String btn_submit_createpage="//button[@id='button-page-create']";
	static final String btn_Actions_Test="//div[@class='dataTables_scrollBody']/table/tbody/tr[1]/td/div/button";
	static final String validation_1stline="//div[@class='swal-modal']/div[2]";
	static final String validation_2ndline="//div[@class='swal-modal']/div[3]";
	static final String validation_btn_cancel="//div[@class='swal-modal']/div[4]/div[1]/button";
	static final String validation_btn_yes="//div[@class='swal-modal']/div[4]/div[2]/button";
	static final String btn_next="//li[@id='PagesTable_next']";
	static final String btn_previous="//li[@id='PagesTable_previous']";
	static final String dd_enteries="//select[@class='custom-select custom-select-sm form-control form-control-sm']";
	static final String entries_25="//select/option[@value='25']";
	static final String entries_10="//select/option[@value='10']";
	static final String txt_entries="//div[contains(text(),'Showing')]";
	static final String btn_search="//button[@class='btn btn-primary']";
	static final String txtbox_search="//input[@class='form-control page-search-filter-text']";
	static final String txt_1st_title="//table[@id='PagesTable']/tbody/tr[1]/td[2]";
	static final String sorting_title="//div[@class='dataTables_scrollHead']//thead/tr/th[2]";
	
}
